
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package analizador;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int ABRIR_LLAVE = 4;
  public static final int ABRIR_CORCHETE = 6;
  public static final int NOMBRE = 34;
  public static final int ENTERO = 23;
  public static final int INT = 20;
  public static final int GALERIA = 38;
  public static final int TITULOY = 29;
  public static final int TITULOX = 28;
  public static final int EJEY = 31;
  public static final int IDENTIFICADOR = 22;
  public static final int SEMICOLON = 12;
  public static final int EJEX = 30;
  public static final int IGUAL = 10;
  public static final int DEFINIRXYLINE = 33;
  public static final int GROSOR = 36;
  public static final int TITULO = 27;
  public static final int ID = 26;
  public static final int CERRAR_PARENTESIS = 3;
  public static final int EOF = 0;
  public static final int PRODUCTO = 16;
  public static final int error = 1;
  public static final int COMA = 13;
  public static final int CADENA = 21;
  public static final int MENOS = 15;
  public static final int GRAFICALINEAS = 25;
  public static final int CERRAR_LLAVE = 5;
  public static final int COLOR = 35;
  public static final int ABRIR_PARENTESIS = 2;
  public static final int PUNTOS = 37;
  public static final int COLON = 11;
  public static final int CERRAR_CORCHETE = 7;
  public static final int ABRIR_INTERROGACION = 8;
  public static final int GRAFICABARRAS = 24;
  public static final int STRING = 19;
  public static final int CERRAR_INTERROGACION = 9;
  public static final int DEFINIR = 18;
  public static final int PUNTOSXY = 32;
  public static final int DIVISION = 17;
  public static final int MAS = 14;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "ABRIR_PARENTESIS",
  "CERRAR_PARENTESIS",
  "ABRIR_LLAVE",
  "CERRAR_LLAVE",
  "ABRIR_CORCHETE",
  "CERRAR_CORCHETE",
  "ABRIR_INTERROGACION",
  "CERRAR_INTERROGACION",
  "IGUAL",
  "COLON",
  "SEMICOLON",
  "COMA",
  "MAS",
  "MENOS",
  "PRODUCTO",
  "DIVISION",
  "DEFINIR",
  "STRING",
  "INT",
  "CADENA",
  "IDENTIFICADOR",
  "ENTERO",
  "GRAFICABARRAS",
  "GRAFICALINEAS",
  "ID",
  "TITULO",
  "TITULOX",
  "TITULOY",
  "EJEX",
  "EJEY",
  "PUNTOSXY",
  "DEFINIRXYLINE",
  "NOMBRE",
  "COLOR",
  "GROSOR",
  "PUNTOS",
  "GALERIA"
  };
}

